### ISSUE TITLE
upload to PyPI

### ISSUE THREAD

**Issue by vfreex** [xning/procszoo#15]
@xning, do you have better description for this project?

**Comment by vfreex** [comment]
I've prepare for uploading.
PKG_INFO created:
```
PKG-INFO 
Metadata-Version: 1.1
Name: procszoo
Version: 0.97.1
Summary: python module to operate Linux namespaces
Home-page: https://github.com/xning/procszoo
Author: xning
Author-email: anzhou94@gmail.com
License: GPLv3+
Description: Procszoo aims to provide you a simple but complete tool and you can use it as a DSL or an embeded programming language which let you operate Linux namespaces by Python.Procszoo gives a smart init program. I get it from baseimage-docker. Thanks a lot, you guys.Procszoo does not require new version Python (but we support python3, too) and Linux kernel.
Keywords: linux container namespace sandbox process
Platform: UNKNOWN
Classifier: Development Status :: 4 - Beta
Classifier: Environment :: Console
Classifier: Intended Audience :: End Users/Desktop
Classifier: Intended Audience :: Developers
Classifier: Intended Audience :: System Administrators
Classifier: Topic :: Software Development :: Libraries
Classifier: Topic :: System :: Systems Administration
Classifier: Intended Audience :: Information Technology
Classifier: License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
Classifier: Programming Language :: Python :: 2
Classifier: Programming Language :: Python :: 2.6
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Operating System :: POSIX :: Linux
```

@xning 
1. Please register an account at https://pypi.python.org, then I will add you to the admin list.
2. Please think about everything you want to change about the package info.

All package info are stored in setup.py, see #16.
Please modify as you need.

**Comment by xning** [comment]
Please wait a day or two for me test and merge your patch. I will register an account today.

**Comment by vfreex** [comment]
Python package versioning:
https://www.python.org/dev/peps/pep-0396/#specification

http://stackoverflow.com/questions/17583443/what-is-the-correct-way-to-share-package-version-with-setup-py-and-the-package

**Comment by xning** [comment]
@vfreex Thats very good links. Is there anything I can do for you now ? I think you can freely update the version number in the setup.py, after you successfully upload, if need we can unify the version and upload again. What do you think? Or we just don't care about the version number in the setup.py.

**Comment by vfreex** [comment]
@xning 
I finally named the first uploaded version as `0.1.1`: https://pypi.python.org/pypi/procszoo/0.1.1
It seems to me that uploaded package is working well.
Try it from PyPI:

``` bash
pip2 install procszoo
# or
pip3 install procszoo
```

**Comment by xning** [comment]
Cool.

2016-08-22 16:16 GMT+08:00 Rayson Zhu <notifications@github.com>:

**Comment by vfreex** [comment]
Just as a reminder:
What I uploaded as version 0.1.1 is the current master commit: f0226768e86d9c5a8681827277df2ca922160a57 .
Maybe we should attach a tag to the commit we released?

**Comment by xning** [comment]
@vfreex yes, I will. You are so cool.

**Comment by xning** [comment]
Thanks a lot, @vfreex  That's so cool to install by 'pip'.
