### ISSUE TITLE
'uninstall' cannot remove dirs

### ISSUE THREAD

**Issue by xning** [xning/procszoo#18]
The install.log don't record dir names, hence dir will left. And install.log lose the easy-install.pth file, too.easy-install.pth

**Comment by xning** [comment]
Shall we unify the install and uninstall by the setuptools? Hence at least we can use pip to unistall it.

**Comment by vfreex** [comment]
So how should we fix it?
Since the package name `procszoo` has been registered to PyPI, maybe we can just call `pip uninstall -y procszoo` to uninstall.

**Comment by xning** [comment]
Except the dirs, we also need edit the easy-install.pth file. Hence, let's first remove the 'install' and 'uninstall' target. And when we find a soltion, then add them again.

**Comment by vfreex** [comment]
targets removed in #21
