### ISSUE TITLE
drop ctypes uses because libffi's bug

### ISSUE THREAD

**Issue by vfreex** [xning/procszoo#3]
This is a long term goal.
As a short-time goal, just tell uses to completely disable SeLinux in /etc/selinux/config.

**Comment by xning** [comment]
Seems only pthread_atfork function cause trouble.

**Comment by vfreex** [comment]
As for the atfork function, I think we just use the new module, otherwise you will need some workarounds to check the SELinux status and judge.
Just keep thing simple.

**Comment by xning** [comment]
If we do that, we need make sure how can we still have it still possible to clone the project and to make then it work.

**Comment by vfreex** [comment]
I think we have made an agreement on this issue. This issue can be closed now.
