### ISSUE TITLE
adding local directory to sys.path was broken

### ISSUE THREAD

**Issue by vfreex** [xning/procszoo#5]
the following statement doesn't work as expected:

``` bash
procszoo_mod_dir = os.path.abspath("%s/.." % os.path.dirname(__file__))
```

if you entered the `tests` directory and run the scripts via a relative path, `os.path.dirname(__file__)` will be empty, so that procszoo_mod_dir will become `/`.

**Comment by xning** [comment]
I will verify this issue and resolve it this night. Thanks.

**Comment by vfreex** [comment]
@xning, I think it's the time to add a `setup.py` to the project, so the project can be uploaded to PyPI.

**Comment by xning** [comment]
I tried, seems the variable works as expect, do I something wrong?

nerd@ubuntu:~/Public/projects/procszoo/tests$ ./test_atfork.py                                                                                                                                               
/home/nerd/Public/projects/procszoo                                                                                                                                                                          
1 56         raise RuntimeError("do fork failed")                                                                                                                                                            
2 57     elif pid == 0:                                                                                                                                                                                      
1 58         printf("child")                                                                                                                                                                                 
child handler:est_atfork.py   Top (9,23)    Git:master  (Py Outl Wrap) Mon Aug 15 15:56 0.23 ----------------------------------------------------------------------------------------------------------------
        cpu: 0 pid: 19676 ppid: 19675
        uid 1000 gid 1000 euid 1000 egid 1000
        hostname: ubuntu.nerd.nay.redhat.com
        procs: 19589, 19631, 19675, 19676
child
parent
nerd@ubuntu:~/Public/projects/procszoo/tests$ python3 ./test_atfork.py 
/home/nerd/Public/projects/procszoo
1
2
1
child handler:
        cpu: 2 pid: 19680 ppid: 19679
        uid 1000 gid 1000 euid 1000 egid 1000
        hostname: b'ubuntu.nerd.nay.redhat.com'
        procs: 19589, 19631, 19679, 19680
child
parent
nerd@ubuntu:~/Public/projects/procszoo/tests$

**Comment by xning** [comment]
I plan to add setup.py after merging your module.

**Comment by vfreex** [comment]
@xning 
`test_atfork.py` has a different implementation:

``` python
procszoo_mod_dir = os.path.abspath("..")
```
But some files does not (including richard_parker):

``` bash
python test_setns.py 
Traceback (most recent call last):
  File "test_setns.py", line 10, in <module>
    from procszoo.c_functions import *
ImportError: No module named procszoo.c_functions
```

Use `python filename.py` not `./filename.py`. It seems those two notations donate different behaviors.

**Comment by xning** [comment]
Got ti. Hence what do you think about this issue?

**Comment by vfreex** [comment]
@xning, confirmed:

Assume we have this script:

``` python
 #!/usr/bin/env python
 
import sys
import os

print('os.path.dirname(__file__)=%s' % os.path.dirname(__file__))
```

if you run `./somefile.py` or `python ./somefile.py`, this statement works:

```
os.path.dirname(__file__)=.
```

but, if you run `python somefile.py` or `somefile.py` (let's say it is in $PATH), that statement will give you an empty string:
```
os.path.dirname(__file__)=
```

then 
```
"%s/.." % os.path.dirname(__file__)=/..
os.path.abspath("%s/.." % os.path.dirname(__file__))=/
```

So the filesystem root will be added to `sys.path`

**Comment by vfreex** [comment]
As a result, if you run these scripts with explicit `python` command without a directory prefix, the procszoo module will not be loaded.

``` python
$ python3 test_pivot_root.py 
Traceback (most recent call last):
  File "test_pivot_root.py", line 9, in <module>
    from procszoo.c_functions import *
ImportError: No module named 'procszoo'
```

**Comment by xning** [comment]
Fixed in commit 6db59131ab17406fdefaa9f9d50d4ec85e70498a, please review and check.

**Comment by vfreex** [comment]
Hey man, it seems you didn't import the function `printf`!
``` bash
$sudo tests/test_setns.py 
Traceback (most recent call last):
  File "tests/test_setns.py", line 22, in <module>
    spawn_namespaces(ns_bind_dir=ns_bind_dir, nscmd=nscmd)
  File "/home/vfreex/Documents/code/upstream/procszoo/procszoo/c_functions/__init__.py", line 1289, in spawn_namespaces
  File "/home/vfreex/Documents/code/upstream/procszoo/procszoo/c_functions/__init__.py", line 1175, in spawn_namespaces
  File "/home/vfreex/Documents/code/upstream/procszoo/procszoo/c_functions/__init__.py", line 968, in _run_cmd_in_new_namespaces
NameError: global name 'printf' is not defined
lo: flags=8<LOOPBACK>  mtu 65536
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

umount /tmp/ns/cgroup by umount2
umount /tmp/ns/ipc by umount2
umount /tmp/ns/net by umount
umount /tmp/ns/pid by umount
umount /tmp/ns/user by umount
umount /tmp/ns/uts by umount
```

**Comment by xning** [comment]
I cannot verify what you said, @vfreex 

nerd@ubuntu:~/Public/projects/procszoo$ sudo tests/test_setns.py 
lo        Link encap:Local Loopback  
          LOOPBACK  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

umount /tmp/ns/cgroup by umount
umount /tmp/ns/ipc by umount
umount /tmp/ns/net by umount2
umount /tmp/ns/pid by umount
umount /tmp/ns/user by umount2
umount /tmp/ns/uts by umount
nerd@ubuntu:~/Public/projects/procszoo$

**Comment by vfreex** [comment]
This issue can be closed now.
