### ISSUE TITLE
move the _default_* method from SpawnNamespacesConfig to other places

### ISSUE THREAD

**Issue by xning** [xning/procszoo#57]
This could be resolved with the issue #55 .

**Comment by xning** [comment]
Perhaps we should move all the content about the SpawnNamespacesConfig to a module.

**Comment by xning** [comment]
No  doubt the *SpawnNamespacesConfig* requires *c_functions*. If we move the *SpawnNamespacesConfig* to a new module, then the two modules will require each other. Sure we can resolve the import issue. But why we do such a hack way. Hence we don't touch the *SpawnNamespacesConfig* any more.

**Comment by vfreex** [comment]
Python has issues when two modules reference each other?
That's pailful! Many modern programming languages don't have this problem!

**Comment by xning** [comment]
@vfreex this could be resolved by some *hack* way. The issue is caused is that when python import a *module*, it is **eval** the module. Hence a dead lock coming if both *import* operations requires each other.

I will close this issue. And if need, you can reopen it.
