### ISSUE TITLE
It seems to me that netlink cannot communicate between PID namespaces

### ISSUE THREAD

**Issue by vfreex** [xning/procszoo#64]
I found rare documents address this issue.
Test code shows that we cannot communicate between different PID namespaces (or we need some workarounds).
Test code:
https://gist.github.com/vfreex/d45f3e1229eeb583fb3d7281ca58bf6b

**Comment by xning** [comment]
@vfreex pls try your code again by put the _socket_ after the _unshare(NEWPID)_. I think because the latter create a new the process file descriptor table and hence cause the demo failed to cross the namespaces. I'm not so sure.

**Comment by xning** [comment]
WWK, @vfreex 
1. PIPE works well when cross namespaces.
2. IOCTL is another old IPC that _ifconfig_ used.
3. _kernel_ is the one but how let it to work for us we don't know.
4. _zeroconfig_ network shows that _richard_parker_ is a cheap version _zookeeper_.

**Comment by vfreex** [comment]
@xning, after whole night's search and investigation, I finally get netlink working.
Because netlink uses PID as identifier by default, we need to fake the identifier to make it global and unique in all namespaces instead of letting kernel choose one for us.
