### ISSUE TITLE
NameError: name 'printf' is not defined

### ISSUE THREAD

**Issue by xning** [xning/procszoo#8]
vfreex reported this issue.

--Call--
> /home/nerd/Public/procszoo/procszoo/c_functions/__init__.py(1279)spawn_namespaces()
-> def spawn_namespaces(namespaces=None, maproot=True, mountproc=True,
(Pdb) printf
*** NameError: name 'printf' is not defined
(Pdb)

**Comment by xning** [comment]
@vfreex , please verify this issue.

**Comment by vfreex** [comment]
verified
