### ISSUE TITLE
how to install procszoo to the system dir?

### ISSUE THREAD

**Issue by xning** [xning/procszoo#9]
Now we just clone and make then could run richard_parker and use the procszoo.c_functions module,  but we need a way to let the procszoo works well after install into the system dir. I think we need a script,
sure some codes need fix, too.

**Comment by vfreex** [comment]
setup.py can handle this, see `https://docs.python.org/2/distutils/setupscript.html#installing-scripts` .
In that case, adding the local directory to sys.path is not necessary.
